apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chinmayee-ingress
  namespace: chinmayee
  annotations:
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: restauranty.diogohack.shop
    http:
      paths:
      - backend:
          service:
            name: auth
            port:
              number: 3001
        path: /api/auth
        pathType: Prefix
      - backend:
          service:
            name: discounts
            port:
              number: 3002
        path: /api/discounts
        pathType: Prefix
      - backend:
          service:
            name: items
            port:
              number: 3003
        path: /api/items
        pathType: Prefix
      - backend:
          service:
            name: frontend
            port:
              number: 80
        path: /
        pathType: Prefix